from .dw_pose_composer import NODE_CLASS_MAPPINGS as P2_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as P2_NAMES
from .dw_identity_multiplexer import NODE_CLASS_MAPPINGS as P3_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as P3_NAMES

NODE_CLASS_MAPPINGS = {**P2_MAPPINGS, **P3_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**P2_NAMES, **P3_NAMES}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
